version: '3'
services:
  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: brasprev
    ports:
      - "5123:5432"
    networks:
      - "my-net"

  microservico:
    image: hbbucker/simple-microservico-jvm:latest
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: .
    ports:
      - "8091:8080"
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/brasprev
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    networks:
      - "my-net"

networks:
  my-net:
    driver: bridge